# Generated by Django 5.2.11 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_designation_examroom_examtype_gradeconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Course Code'),
        ),
    ]
