# Generated by Django 5.2.11 on 2026-02-15 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_companyinternship_internshipapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.branch'),
        ),
    ]
