# Generated by Django 5.2.11 on 2026-02-15 16:16

from django.db import migrations, models


def map_attendance_status(apps, schema_editor):
    AttendanceReport = apps.get_model('main_app', 'AttendanceReport')
    AttendanceReport.objects.filter(status__in=['1', 'True', 'true', 1, True]).update(status='present')
    AttendanceReport.objects.filter(status__in=['0', 'False', 'false', 0, False, None, '']).update(status='absent')


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('medical', 'Medical Leave')], default='absent', max_length=10),
        ),
        migrations.RunPython(map_attendance_status, migrations.RunPython.noop),
    ]
