# Generated by Django 5.2.11 on 2026-02-15 16:29

import django.db.models.deletion
from django.contrib.auth.hashers import make_password
from django.conf import settings
from django.db import migrations, models


def create_authority_user(apps, schema_editor):
    CustomUser = apps.get_model('main_app', 'CustomUser')
    Authority = apps.get_model('main_app', 'Authority')
    email = 'authorityx@aegis.local'
    user = CustomUser.objects.filter(email=email).first()
    if not user:
        user = CustomUser.objects.create(
            email=email,
            password=make_password('xyz'),
            user_type='4',
            gender='M',
            address='Authority account',
            profile_pic='defaults/profile.png',
            first_name='Authority',
            last_name='User',
            is_active=True,
        )
    if not Authority.objects.filter(admin=user).exists():
        Authority.objects.create(admin=user)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_attendancereport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Faculty'), (3, 'Student'), (4, 'Authority')], default=1, max_length=1),
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_authority_user, migrations.RunPython.noop),
    ]
