# Generated by Django 5.2.11 on 2026-02-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_discussionpost_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Exam Period'), ('registration', 'Registration'), ('semester_start', 'Semester Start'), ('semester_end', 'Semester End'), ('event', 'Campus Event'), ('deadline', 'Important Deadline'), ('other', 'Other')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to='main_app.session')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('mid_term', 'Mid Term'), ('end_term', 'End Term'), ('quiz', 'Quiz'), ('assignment', 'Assignment'), ('practical', 'Practical'), ('viva', 'Viva')], max_length=20)),
                ('exam_date', models.DateField()),
                ('exam_time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('syllabus', models.TextField(blank=True, help_text='Topics/chapters to be covered')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to='main_app.staff')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_dates', to='main_app.subject')),
            ],
            options={
                'ordering': ['exam_date', 'exam_time'],
            },
        ),
    ]
